### PR TITLE
update minikube demo and cnspec commands

### PR DESCRIPTION
**Pull request by atomic111**
Signed-off-by: Patrick Münch <patrick.muench1111@gmail.com>

### CODE REVIEW

**Review by scottford-io — DISMISSED** [review]
Looks good @atomic111 🙌

**Comment by mm-weber** [comment]
Looks good to me

**Review by mm-weber — DISMISSED** [review]
LGTM

**Review by mm-weber — APPROVED** [review]
LGTM

**Review by mm-weber — APPROVED** [review]
LGTM

**Pull request merged**
